name: first workflow
env:
  WORKFLOW_VAR: "Declared at workflow level"
  
on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World!  This is the first job
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Shakira'
      - name: time
        run: |
          echo "The time of the greeting was ${{ steps.greetings.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "Defined in secondjob"
    steps:
      - name: secondJob script
        env:
          STEP_VAR: "Defined at step level"
        shell: bash
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
          echo "The following are default environment variables:"
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF
